const PDFDocument = require("pdfkit");

function addList(doc, title, items) {
  doc.moveDown(0.5).fontSize(12).text(title, { underline: true });
  doc.moveDown(0.2).fontSize(11);
  if (!items || !items.length) {
    doc.text("- (none)");
    return;
  }
  items.forEach((i) => doc.text(`- ${i}`));
}

async function makePdfBuffer(item) {
  return new Promise((resolve) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    doc.fontSize(18).text("ESL Assessment Validity Report");
    doc.moveDown(0.5).fontSize(11).text(`Report ID: ${item.id}`);
    doc.fontSize(11).text(`Created: ${item.createdAt}`);
    doc.fontSize(11).text(`Mode: ${item.mode}`);

    doc.moveDown();
    doc.fontSize(13).text("Task Info", { underline: true });
    doc.moveDown(0.2).fontSize(11);
    doc.text(`Skill: ${item.input?.skill || ""}`);
    doc.text(`Framework: ${item.input?.levelFramework || ""}`);
    doc.text(`Level: ${item.input?.level || ""}`);
    doc.text(`Purpose: ${item.input?.purpose || ""}`);

    doc.moveDown();
    doc.fontSize(13).text("Summary", { underline: true });
    doc.moveDown(0.2).fontSize(11).text(item.output?.summary || "");

    addList(doc, "Strengths", item.output?.strengths || []);
    addList(doc, "Issues", item.output?.issues || []);
    addList(doc, "Suggestions", item.output?.suggestions || []);

    doc.moveDown();
    doc.fontSize(10).text("Generated by ESL Validity Tool Backend", { opacity: 0.8 });

    doc.end();
  });
}

module.exports = { makePdfBuffer };
